services:
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
